# Generated by Django 5.0.1 on 2024-01-24 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0002_delete_user_alter_userinfo_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='confirmpassword',
            new_name='confirm_password',
        ),
    ]
